# Application name. spring \u9879\u76EE\u7684\u540D\u79F0
spring:
  application:
    name: spring-boot-learn-examples-v1-jar
    
# Server HTTP port.\u7AEF\u53E3\u53F7
server:
  port: 9090

  
friedns:
  name: zhangsan
  age: 20
  
users: {name: zhangsan,gae: 30}

lists: 
  - zhangsan
  - lisi
  